// Service wiring for specs/design/components/todo-api/openapi.yaml.
// Generated by `bal openapi --mode service`, then every resource body filled
// in against the lists/tasks/members/notifications repositories.

import ballerina/http;

listener http:Listener ep0 = new (9090);

service / on ep0 {
    # List todo lists the caller owns or collaborates on
    resource function get lists(@http:Header string? X\-User\-Id, int 'limit = 20, int offset = 0) returns inline_response_200|ErrorUnauthorized|error {
        string|ErrorUnauthorized userId = requireUserId(X\-User\-Id);
        if userId is ErrorUnauthorized {
            return userId;
        }
        int pageLimit = clampLimit('limit);
        int pageOffset = clampOffset(offset);
        [TodoList[], int] [lists, count] = check listListsForUser(userId, pageLimit, pageOffset);
        [string?, string?] [next, previous] = buildPageLinks("/lists", "", pageLimit, pageOffset, count);
        return {count: count, next: next, previous: previous, data: lists};
    }

    # Create a new todo list owned by the caller
    resource function post lists(@http:Header string? X\-User\-Id, @http:Payload NewList payload) returns TodoList|ErrorBadRequest|ErrorUnauthorized|error {
        string|ErrorUnauthorized userId = requireUserId(X\-User\-Id);
        if userId is ErrorUnauthorized {
            return userId;
        }
        if payload.name.trim().length() == 0 {
            return badRequestError("name is required");
        }
        return check createList(payload.name, userId);
    }

    # Get a todo list
    resource function get lists/[string listId](@http:Header string? X\-User\-Id) returns TodoList|ErrorNotFound|ErrorUnauthorized|error {
        string|ErrorUnauthorized userId = requireUserId(X\-User\-Id);
        if userId is ErrorUnauthorized {
            return userId;
        }
        TodoList? list = check getViewableList(listId, userId);
        if list is () {
            return notFoundError("list not found");
        }
        return list;
    }

    # Rename a todo list
    resource function patch lists/[string listId](@http:Header string? X\-User\-Id, @http:Payload ListUpdate payload) returns TodoList|ErrorBadRequest|ErrorNotFound|ErrorUnauthorized|error {
        string|ErrorUnauthorized userId = requireUserId(X\-User\-Id);
        if userId is ErrorUnauthorized {
            return userId;
        }
        string? newName = payload?.name;
        if newName is () || newName.trim().length() == 0 {
            return badRequestError("name is required");
        }
        TodoList? updated = check renameList(listId, userId, newName);
        if updated is () {
            return notFoundError("list not found");
        }
        return updated;
    }

    # Delete a todo list (owner only)
    resource function delete lists/[string listId](@http:Header string? X\-User\-Id) returns http:NoContent|ErrorForbidden|ErrorNotFound|ErrorUnauthorized|error {
        string|ErrorUnauthorized userId = requireUserId(X\-User\-Id);
        if userId is ErrorUnauthorized {
            return userId;
        }
        ListDeleteOutcome outcome = check deleteList(listId, userId);
        if outcome == "notfound" {
            return notFoundError("list not found");
        }
        if outcome == "forbidden" {
            return forbiddenError("only the owner may delete this list");
        }
        return http:NO_CONTENT;
    }

    # List a list's owner and collaborators
    resource function get lists/[string listId]/members(@http:Header string? X\-User\-Id) returns Member[]|ErrorNotFound|ErrorUnauthorized|error {
        string|ErrorUnauthorized userId = requireUserId(X\-User\-Id);
        if userId is ErrorUnauthorized {
            return userId;
        }
        TodoList? list = check getViewableList(listId, userId);
        if list is () {
            return notFoundError("list not found");
        }
        return check listMembersRows(listId);
    }

    # Invite a collaborator to the list by email
    resource function post lists/[string listId]/members(@http:Header string? X\-User\-Id, @http:Payload Invitation payload) returns Member|ErrorBadRequest|ErrorForbidden|ErrorNotFound|ErrorUnauthorized|error {
        string|ErrorUnauthorized userId = requireUserId(X\-User\-Id);
        if userId is ErrorUnauthorized {
            return userId;
        }
        TodoList? list = check getListRow(listId);
        if list is () {
            return notFoundError("list not found");
        }
        if list.ownerId != userId {
            return forbiddenError("only the owner may invite collaborators");
        }
        if payload.email.trim().length() == 0 {
            return badRequestError("email is required");
        }
        InviteResult|InviteOutcome result = check inviteMember(listId, payload.email);
        if result is InviteOutcome {
            return badRequestError("this email is already a member of the list");
        }
        check createNotification(result.member.userId, "invitation", "You were invited to collaborate on \"" + list.name + "\"", result.invitationId);
        return result.member;
    }

    # Remove a collaborator, or leave the list as the caller
    resource function delete lists/[string listId]/members/[string userId](@http:Header string? X\-User\-Id) returns http:NoContent|ErrorForbidden|ErrorNotFound|ErrorUnauthorized|error {
        string|ErrorUnauthorized callerId = requireUserId(X\-User\-Id);
        if callerId is ErrorUnauthorized {
            return callerId;
        }
        RemoveOutcome outcome = check removeMember(listId, userId, callerId);
        if outcome == "notfound" {
            return notFoundError("list or member not found");
        }
        if outcome == "forbidden" {
            return forbiddenError("caller may not remove this member");
        }
        return http:NO_CONTENT;
    }

    # Accept a pending invitation and join the list as a collaborator
    resource function post invitations/[string invitationId]/accept(@http:Header string? X\-User\-Id) returns TodoListOk|ErrorNotFound|ErrorUnauthorized|error {
        string|ErrorUnauthorized userId = requireUserId(X\-User\-Id);
        if userId is ErrorUnauthorized {
            return userId;
        }
        TodoList? list = check acceptInvitation(invitationId, userId);
        if list is () {
            return notFoundError("invitation not found");
        }
        return <TodoListOk>{body: list};
    }

    # List tasks on a list, filterable and sortable
    resource function get lists/[string listId]/tasks(@http:Header string? X\-User\-Id, "low"|"medium"|"high"? priority, string? category, string? assigneeId, boolean? completed, "dueDate"|"priority"? sort, int 'limit = 20, int offset = 0) returns inline_response_200_1|ErrorNotFound|ErrorUnauthorized|error {
        string|ErrorUnauthorized userId = requireUserId(X\-User\-Id);
        if userId is ErrorUnauthorized {
            return userId;
        }
        TodoList? list = check getViewableList(listId, userId);
        if list is () {
            return notFoundError("list not found");
        }
        int pageLimit = clampLimit('limit);
        int pageOffset = clampOffset(offset);
        [Task[], int] [tasks, count] = check listTasksForList(listId, priority, category, assigneeId, completed, sort, pageLimit, pageOffset);
        string extraQuery = buildTasksExtraQuery(priority, category, assigneeId, completed, sort);
        [string?, string?] [next, previous] = buildPageLinks("/lists/" + listId + "/tasks", extraQuery, pageLimit, pageOffset, count);
        return {count: count, next: next, previous: previous, data: tasks};
    }

    # Add a task to a list
    resource function post lists/[string listId]/tasks(@http:Header string? X\-User\-Id, @http:Payload NewTask payload) returns Task|ErrorBadRequest|ErrorNotFound|ErrorUnauthorized|error {
        string|ErrorUnauthorized userId = requireUserId(X\-User\-Id);
        if userId is ErrorUnauthorized {
            return userId;
        }
        if payload.title.trim().length() == 0 {
            return badRequestError("title is required");
        }
        Task|"notfound"|"badrequest" result = check createTask(listId, userId, payload);
        if result == "notfound" {
            return notFoundError("list not found");
        }
        if result == "badrequest" {
            return badRequestError("assigneeId is not a collaborator on this list");
        }
        return result;
    }

    # Get a task
    resource function get tasks/[string taskId](@http:Header string? X\-User\-Id) returns Task|ErrorNotFound|ErrorUnauthorized|error {
        string|ErrorUnauthorized userId = requireUserId(X\-User\-Id);
        if userId is ErrorUnauthorized {
            return userId;
        }
        Task? task = check getAuthorizedTask(taskId, userId);
        if task is () {
            return notFoundError("task not found");
        }
        return task;
    }

    # Update a task's title, due date, priority, categories, assignee, or completion
    resource function patch tasks/[string taskId](@http:Header string? X\-User\-Id, @http:Payload TaskUpdate payload) returns Task|ErrorBadRequest|ErrorNotFound|ErrorUnauthorized|error {
        string|ErrorUnauthorized userId = requireUserId(X\-User\-Id);
        if userId is ErrorUnauthorized {
            return userId;
        }
        Task|"notfound"|"badrequest" result = check updateTask(taskId, userId, payload);
        if result == "notfound" {
            return notFoundError("task not found");
        }
        if result == "badrequest" {
            return badRequestError("assigneeId is not a collaborator on this list");
        }
        return result;
    }

    # Delete a task
    resource function delete tasks/[string taskId](@http:Header string? X\-User\-Id) returns http:NoContent|ErrorNotFound|ErrorUnauthorized|error {
        string|ErrorUnauthorized userId = requireUserId(X\-User\-Id);
        if userId is ErrorUnauthorized {
            return userId;
        }
        "deleted"|"notfound" outcome = check deleteTask(taskId, userId);
        if outcome == "notfound" {
            return notFoundError("task not found");
        }
        return http:NO_CONTENT;
    }

    # List the caller's in-app notifications
    resource function get notifications(@http:Header string? X\-User\-Id, boolean? unreadOnly, int 'limit = 20, int offset = 0) returns inline_response_200_2|ErrorUnauthorized|error {
        string|ErrorUnauthorized userId = requireUserId(X\-User\-Id);
        if userId is ErrorUnauthorized {
            return userId;
        }
        int pageLimit = clampLimit('limit);
        int pageOffset = clampOffset(offset);
        [Notification[], int] [notifications, count] = check listNotificationsForUser(userId, unreadOnly, pageLimit, pageOffset);
        string extraQuery = buildNotificationsExtraQuery(unreadOnly);
        [string?, string?] [next, previous] = buildPageLinks("/notifications", extraQuery, pageLimit, pageOffset, count);
        return {count: count, next: next, previous: previous, data: notifications};
    }

    # Mark a notification as read
    resource function patch notifications/[string notificationId](@http:Header string? X\-User\-Id, @http:Payload notifications_notificationId_body payload) returns Notification|ErrorNotFound|ErrorUnauthorized|error {
        string|ErrorUnauthorized userId = requireUserId(X\-User\-Id);
        if userId is ErrorUnauthorized {
            return userId;
        }
        Notification? updated = check markNotificationRead(notificationId, userId, payload.read);
        if updated is () {
            return notFoundError("notification not found");
        }
        return updated;
    }
}
